//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: newFriendMessage.proto

package grpc_code_gen.friend.friendMessage;

@kotlin.jvm.JvmName("-initializenewFriendMessageReply")
public inline fun newFriendMessageReply(block: grpc_code_gen.friend.friendMessage.newFriendMessageReplyKt.Dsl.() -> kotlin.Unit): grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply =
  grpc_code_gen.friend.friendMessage.newFriendMessageReplyKt.Dsl._create(grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply.newBuilder()).apply { block() }._build()
public object newFriendMessageReplyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply = _builder.build()

    /**
     * <code>int64 uid = 1;</code>
     */
    public var uid: kotlin.Long
      @JvmName("getUid")
      get() = _builder.getUid()
      @JvmName("setUid")
      set(value) {
        _builder.setUid(value)
      }
    /**
     * <code>int64 uid = 1;</code>
     */
    public fun clearUid() {
      _builder.clearUid()
    }

    /**
     * <code>string user_name = 2;</code>
     */
    public var userName: kotlin.String
      @JvmName("getUserName")
      get() = _builder.getUserName()
      @JvmName("setUserName")
      set(value) {
        _builder.setUserName(value)
      }
    /**
     * <code>string user_name = 2;</code>
     */
    public fun clearUserName() {
      _builder.clearUserName()
    }

    /**
     * <code>int32 sex = 3;</code>
     */
    public var sex: kotlin.Int
      @JvmName("getSex")
      get() = _builder.getSex()
      @JvmName("setSex")
      set(value) {
        _builder.setSex(value)
      }
    /**
     * <code>int32 sex = 3;</code>
     */
    public fun clearSex() {
      _builder.clearSex()
    }

    /**
     * <code>string birthday_date = 4;</code>
     */
    public var birthdayDate: kotlin.String
      @JvmName("getBirthdayDate")
      get() = _builder.getBirthdayDate()
      @JvmName("setBirthdayDate")
      set(value) {
        _builder.setBirthdayDate(value)
      }
    /**
     * <code>string birthday_date = 4;</code>
     */
    public fun clearBirthdayDate() {
      _builder.clearBirthdayDate()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply.copy(block: grpc_code_gen.friend.friendMessage.newFriendMessageReplyKt.Dsl.() -> kotlin.Unit): grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply =
  grpc_code_gen.friend.friendMessage.newFriendMessageReplyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

