//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: newFriendMessage.proto

package grpc_code_gen.friend.friendMessage;

@kotlin.jvm.JvmName("-initializenewFriendMessageRequest")
public inline fun newFriendMessageRequest(block: grpc_code_gen.friend.friendMessage.newFriendMessageRequestKt.Dsl.() -> kotlin.Unit): grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest =
  grpc_code_gen.friend.friendMessage.newFriendMessageRequestKt.Dsl._create(grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest.newBuilder()).apply { block() }._build()
public object newFriendMessageRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest = _builder.build()

    /**
     * <code>int64 id = 1;</code>
     */
    public var id: kotlin.Long
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>int64 id = 1;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest.copy(block: grpc_code_gen.friend.friendMessage.newFriendMessageRequestKt.Dsl.() -> kotlin.Unit): grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest =
  grpc_code_gen.friend.friendMessage.newFriendMessageRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

