// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: newFriend.proto

package grpc_code_gen.friend.newFriend;

public final class NewFriend {
  private NewFriend() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface newFriendRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:newFriendRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.newFriendMessageRequest id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>.newFriendMessageRequest id = 1;</code>
     * @return The id.
     */
    grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest getId();
    /**
     * <code>.newFriendMessageRequest id = 1;</code>
     */
    grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequestOrBuilder getIdOrBuilder();
  }
  /**
   * Protobuf type {@code newFriendRequest}
   */
  public static final class newFriendRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:newFriendRequest)
      newFriendRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use newFriendRequest.newBuilder() to construct.
    private newFriendRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private newFriendRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new newFriendRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc_code_gen.friend.newFriend.NewFriend.internal_static_newFriendRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc_code_gen.friend.newFriend.NewFriend.internal_static_newFriendRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest.class, grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest id_;
    /**
     * <code>.newFriendMessageRequest id = 1;</code>
     * @return Whether the id field is set.
     */
    @java.lang.Override
    public boolean hasId() {
      return id_ != null;
    }
    /**
     * <code>.newFriendMessageRequest id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest getId() {
      return id_ == null ? grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest.getDefaultInstance() : id_;
    }
    /**
     * <code>.newFriendMessageRequest id = 1;</code>
     */
    @java.lang.Override
    public grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequestOrBuilder getIdOrBuilder() {
      return id_ == null ? grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest.getDefaultInstance() : id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != null) {
        output.writeMessage(1, getId());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest)) {
        return super.equals(obj);
      }
      grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest other = (grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (!getId()
            .equals(other.getId())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code newFriendRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:newFriendRequest)
        grpc_code_gen.friend.newFriend.NewFriend.newFriendRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc_code_gen.friend.newFriend.NewFriend.internal_static_newFriendRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc_code_gen.friend.newFriend.NewFriend.internal_static_newFriendRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest.class, grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest.Builder.class);
      }

      // Construct using grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = null;
        if (idBuilder_ != null) {
          idBuilder_.dispose();
          idBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc_code_gen.friend.newFriend.NewFriend.internal_static_newFriendRequest_descriptor;
      }

      @java.lang.Override
      public grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest getDefaultInstanceForType() {
        return grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest.getDefaultInstance();
      }

      @java.lang.Override
      public grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest build() {
        grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest buildPartial() {
        grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest result = new grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = idBuilder_ == null
              ? id_
              : idBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest) {
          return mergeFrom((grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest other) {
        if (other == grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          mergeId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getIdFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest id_;
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest, grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest.Builder, grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequestOrBuilder> idBuilder_;
      /**
       * <code>.newFriendMessageRequest id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.newFriendMessageRequest id = 1;</code>
       * @return The id.
       */
      public grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest getId() {
        if (idBuilder_ == null) {
          return id_ == null ? grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest.getDefaultInstance() : id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>.newFriendMessageRequest id = 1;</code>
       */
      public Builder setId(grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
        } else {
          idBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.newFriendMessageRequest id = 1;</code>
       */
      public Builder setId(
          grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.newFriendMessageRequest id = 1;</code>
       */
      public Builder mergeId(grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest value) {
        if (idBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            id_ != null &&
            id_ != grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest.getDefaultInstance()) {
            getIdBuilder().mergeFrom(value);
          } else {
            id_ = value;
          }
        } else {
          idBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.newFriendMessageRequest id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = null;
        if (idBuilder_ != null) {
          idBuilder_.dispose();
          idBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.newFriendMessageRequest id = 1;</code>
       */
      public grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest.Builder getIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.newFriendMessageRequest id = 1;</code>
       */
      public grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequestOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_ == null ?
              grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest.getDefaultInstance() : id_;
        }
      }
      /**
       * <code>.newFriendMessageRequest id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest, grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest.Builder, grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequestOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest, grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequest.Builder, grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageRequestOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:newFriendRequest)
    }

    // @@protoc_insertion_point(class_scope:newFriendRequest)
    private static final grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest();
    }

    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<newFriendRequest>
        PARSER = new com.google.protobuf.AbstractParser<newFriendRequest>() {
      @java.lang.Override
      public newFriendRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<newFriendRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<newFriendRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc_code_gen.friend.newFriend.NewFriend.newFriendRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface newFriendReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:newFriendReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.newFriendMessageReply message = 1;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>.newFriendMessageReply message = 1;</code>
     * @return The message.
     */
    grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply getMessage();
    /**
     * <code>.newFriendMessageReply message = 1;</code>
     */
    grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReplyOrBuilder getMessageOrBuilder();
  }
  /**
   * Protobuf type {@code newFriendReply}
   */
  public static final class newFriendReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:newFriendReply)
      newFriendReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use newFriendReply.newBuilder() to construct.
    private newFriendReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private newFriendReply() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new newFriendReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc_code_gen.friend.newFriend.NewFriend.internal_static_newFriendReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc_code_gen.friend.newFriend.NewFriend.internal_static_newFriendReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc_code_gen.friend.newFriend.NewFriend.newFriendReply.class, grpc_code_gen.friend.newFriend.NewFriend.newFriendReply.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply message_;
    /**
     * <code>.newFriendMessageReply message = 1;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return message_ != null;
    }
    /**
     * <code>.newFriendMessageReply message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply getMessage() {
      return message_ == null ? grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply.getDefaultInstance() : message_;
    }
    /**
     * <code>.newFriendMessageReply message = 1;</code>
     */
    @java.lang.Override
    public grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReplyOrBuilder getMessageOrBuilder() {
      return message_ == null ? grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply.getDefaultInstance() : message_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (message_ != null) {
        output.writeMessage(1, getMessage());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (message_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMessage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof grpc_code_gen.friend.newFriend.NewFriend.newFriendReply)) {
        return super.equals(obj);
      }
      grpc_code_gen.friend.newFriend.NewFriend.newFriendReply other = (grpc_code_gen.friend.newFriend.NewFriend.newFriendReply) obj;

      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc_code_gen.friend.newFriend.NewFriend.newFriendReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code newFriendReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:newFriendReply)
        grpc_code_gen.friend.newFriend.NewFriend.newFriendReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc_code_gen.friend.newFriend.NewFriend.internal_static_newFriendReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc_code_gen.friend.newFriend.NewFriend.internal_static_newFriendReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc_code_gen.friend.newFriend.NewFriend.newFriendReply.class, grpc_code_gen.friend.newFriend.NewFriend.newFriendReply.Builder.class);
      }

      // Construct using grpc_code_gen.friend.newFriend.NewFriend.newFriendReply.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        message_ = null;
        if (messageBuilder_ != null) {
          messageBuilder_.dispose();
          messageBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc_code_gen.friend.newFriend.NewFriend.internal_static_newFriendReply_descriptor;
      }

      @java.lang.Override
      public grpc_code_gen.friend.newFriend.NewFriend.newFriendReply getDefaultInstanceForType() {
        return grpc_code_gen.friend.newFriend.NewFriend.newFriendReply.getDefaultInstance();
      }

      @java.lang.Override
      public grpc_code_gen.friend.newFriend.NewFriend.newFriendReply build() {
        grpc_code_gen.friend.newFriend.NewFriend.newFriendReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public grpc_code_gen.friend.newFriend.NewFriend.newFriendReply buildPartial() {
        grpc_code_gen.friend.newFriend.NewFriend.newFriendReply result = new grpc_code_gen.friend.newFriend.NewFriend.newFriendReply(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(grpc_code_gen.friend.newFriend.NewFriend.newFriendReply result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.message_ = messageBuilder_ == null
              ? message_
              : messageBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc_code_gen.friend.newFriend.NewFriend.newFriendReply) {
          return mergeFrom((grpc_code_gen.friend.newFriend.NewFriend.newFriendReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc_code_gen.friend.newFriend.NewFriend.newFriendReply other) {
        if (other == grpc_code_gen.friend.newFriend.NewFriend.newFriendReply.getDefaultInstance()) return this;
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMessageFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply message_;
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply, grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply.Builder, grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReplyOrBuilder> messageBuilder_;
      /**
       * <code>.newFriendMessageReply message = 1;</code>
       * @return Whether the message field is set.
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.newFriendMessageReply message = 1;</code>
       * @return The message.
       */
      public grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply getMessage() {
        if (messageBuilder_ == null) {
          return message_ == null ? grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply.getDefaultInstance() : message_;
        } else {
          return messageBuilder_.getMessage();
        }
      }
      /**
       * <code>.newFriendMessageReply message = 1;</code>
       */
      public Builder setMessage(grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
        } else {
          messageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.newFriendMessageReply message = 1;</code>
       */
      public Builder setMessage(
          grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply.Builder builderForValue) {
        if (messageBuilder_ == null) {
          message_ = builderForValue.build();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.newFriendMessageReply message = 1;</code>
       */
      public Builder mergeMessage(grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply value) {
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            message_ != null &&
            message_ != grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply.getDefaultInstance()) {
            getMessageBuilder().mergeFrom(value);
          } else {
            message_ = value;
          }
        } else {
          messageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.newFriendMessageReply message = 1;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        message_ = null;
        if (messageBuilder_ != null) {
          messageBuilder_.dispose();
          messageBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.newFriendMessageReply message = 1;</code>
       */
      public grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply.Builder getMessageBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.newFriendMessageReply message = 1;</code>
       */
      public grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReplyOrBuilder getMessageOrBuilder() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          return message_ == null ?
              grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply.getDefaultInstance() : message_;
        }
      }
      /**
       * <code>.newFriendMessageReply message = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply, grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply.Builder, grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReplyOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply, grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReply.Builder, grpc_code_gen.friend.friendMessage.NewFriendMessage.newFriendMessageReplyOrBuilder>(
                  getMessage(),
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:newFriendReply)
    }

    // @@protoc_insertion_point(class_scope:newFriendReply)
    private static final grpc_code_gen.friend.newFriend.NewFriend.newFriendReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc_code_gen.friend.newFriend.NewFriend.newFriendReply();
    }

    public static grpc_code_gen.friend.newFriend.NewFriend.newFriendReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<newFriendReply>
        PARSER = new com.google.protobuf.AbstractParser<newFriendReply>() {
      @java.lang.Override
      public newFriendReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<newFriendReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<newFriendReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public grpc_code_gen.friend.newFriend.NewFriend.newFriendReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newFriendRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newFriendRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_newFriendReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_newFriendReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017newFriend.proto\032\026newFriendMessage.prot" +
      "o\"8\n\020newFriendRequest\022$\n\002id\030\001 \001(\0132\030.newF" +
      "riendMessageRequest\"9\n\016newFriendReply\022\'\n" +
      "\007message\030\001 \001(\0132\026.newFriendMessageReply2;" +
      "\n\rfriendMessage\022*\n\004find\022\021.newFriendReque" +
      "st\032\017.newFriendReplyB \n\036grpc_code_gen.fri" +
      "end.newFriendb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          grpc_code_gen.friend.friendMessage.NewFriendMessage.getDescriptor(),
        });
    internal_static_newFriendRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_newFriendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newFriendRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_newFriendReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_newFriendReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_newFriendReply_descriptor,
        new java.lang.String[] { "Message", });
    grpc_code_gen.friend.friendMessage.NewFriendMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
